"""Regenerate `00-index.md` for a docs directory from frontmatter.

INPUT:        <docs-dir> [--all] [--dry-run].
OUTPUT:       rewrites each dir's 00-index.md between BEGIN/END markers; exit 1 on bad dir.
DEPENDENCIES: docs/**/*.md frontmatter.
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

# This script lives at src/scripts/; the package lives at src/core/thinking_os.
# Resolve it explicitly so `tools.docs` imports under bare python3 (no PYTHONPATH).
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_THINKING_OS = _REPO_ROOT / "src" / "core" / "thinking_os"
sys.path.insert(0, str(_THINKING_OS))
sys.path.insert(0, str(_THINKING_OS.parent))

from tools.docs import list_doc_headers

BEGIN_MARKER = "<!-- BEGIN auto-index -->"
END_MARKER = "<!-- END auto-index -->"

# Layer ordering for the rendered index — most actionable first.
_LAYER_ORDER = [
    "index",
    "policy",
    "playbook",
    "runbook",
    "spec",
    "adr",
    "postmortem",
    "reference",
    "task",
]


def _layer_sort_key(layer: str) -> tuple[int, str]:
    if layer in _LAYER_ORDER:
        return (_LAYER_ORDER.index(layer), layer)
    return (len(_LAYER_ORDER), layer)


def _link_target(index_dir: Path, header_path: Path) -> str:
    """Return a relative POSIX path from index_dir to header_path."""
    try:
        rel = header_path.resolve().relative_to(index_dir.resolve())
    except ValueError:
        # Different drives or unrelated trees — fall back to absolute.
        return str(header_path)
    return rel.as_posix()


def _render_index(directory: Path, headers: list[dict]) -> str:
    """Build the auto-index markdown body for `directory`."""
    grouped: dict[str, list[dict]] = defaultdict(list)
    for header in headers:
        # Skip the index file itself if it parsed.
        if Path(header["path"]).name == "00-index.md":
            continue
        layer = header["frontmatter"].get("layer") or "reference"
        grouped[layer].append(header)

    lines: list[str] = []
    lines.append(BEGIN_MARKER)
    lines.append(f"<!-- generated by scripts/regen_doc_index.py on {date.today().isoformat()} -->")
    if not grouped:
        lines.append("")
        lines.append("_No canonical-frontmatter docs in this directory yet._")
        lines.append(END_MARKER)
        return "\n".join(lines) + "\n"

    for layer in sorted(grouped.keys(), key=_layer_sort_key):
        rows = grouped[layer]
        lines.append("")
        lines.append(f"### {layer.title()} ({len(rows)})")
        lines.append("")
        for header in rows:
            link = _link_target(directory, Path(header["path"]))
            title = header["title"] or Path(header["path"]).stem
            updated = header["frontmatter"].get("updated") or "n/a"
            ssot = header["frontmatter"].get("ssot") or "ref"
            tokens = header["frontmatter"].get("tokens")
            tag = f"`ssot:{ssot}`"
            if tokens:
                tag += f" `~{tokens}t`"
            lines.append(f"- [{title}]({link}) — {tag} · updated {updated}")
    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines) + "\n"


def _splice_into_existing(existing: str, regenerated: str) -> str:
    """Replace the auto-index fence inside `existing`, keep the rest."""
    if BEGIN_MARKER not in existing or END_MARKER not in existing:
        return regenerated
    pre = existing.split(BEGIN_MARKER, 1)[0]
    post = existing.split(END_MARKER, 1)[1]
    return f"{pre}{regenerated}{post}"


def regenerate(directory: Path, *, write: bool = True) -> str | None:
    """Regenerate `00-index.md` for one directory.

    Returns the new file body, or None when the directory holds no
    canonical-frontmatter docs (caller decides whether to warn).
    """
    headers = list_doc_headers(directory, limit=500)
    headers = [h for h in headers if Path(h["path"]).parent.resolve() == directory.resolve()]
    if not headers:
        return None
    auto_section = _render_index(directory, headers)
    target = directory / "00-index.md"
    if target.exists():
        existing = target.read_text(encoding="utf-8")
        new_body = _splice_into_existing(existing, auto_section)
    else:
        # First-time index — wrap with a minimal frontmatter so it follows
        # docs-system.md’s Navigation Rules contract. Mixed-domain dirs
        # (e.g. /benchmarks holding ALL + INFRA + CORE files) get
        # `domain:ALL` per TASK-162 fix #7. A homogeneous dir keeps its
        # single domain so cos_doc_headers_by(domain=…) routing stays
        # tight.
        domains = {h["frontmatter"].get("domain", "DOCS") for h in headers}
        if len(domains) > 1:
            domain = "ALL"
        else:
            domain = next(iter(domains)) or "DOCS"
        new_body = (
            f"<!-- domain:{domain} | layer:index | ssot:true | updated:{date.today().isoformat()} -->\n"
            f"# {directory.name} Index\n\n"
            "Purpose: Auto-generated routing hub for this directory.\n"
            "Read when: Locating the canonical doc for the active task.\n"
            "Skip when: A higher-level index already routed you to the target file.\n"
            "Read next: any of the entries below.\n\n"
            "> Nav: [Docs Index](../00-index.md)\n\n"
            f"{auto_section}"
        )
    if write:
        # Atomic write: the auto-regen hook fires fire-and-forget, so
        # two concurrent regens of one dir could interleave a partial write and
        # corrupt 00-index. tmp-in-same-dir + replace() makes the swap atomic.
        tmp = target.with_name(target.name + ".regen.tmp")
        tmp.write_text(new_body, encoding="utf-8")
        tmp.replace(target)
    return new_body


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "directory", nargs="?", default="docs", help="Directory to index (default: docs)"
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Print the regenerated index instead of writing"
    )
    parser.add_argument(
        "--all", action="store_true", help="Recurse into every subdir with ≥2 frontmatter docs"
    )
    args = parser.parse_args(argv)

    root = Path(args.directory)
    if not root.is_dir():
        print(f"ERROR: not a directory: {root}", file=sys.stderr)
        return 1

    targets: list[Path]
    if args.all:
        # Walk every subdir; only those with ≥2 canonical docs index.
        targets = sorted(
            {p.parent.resolve() for p in root.rglob("*.md") if p.name != "00-index.md"}
        )
    else:
        targets = [root]

    written = 0
    skipped = 0
    for directory in targets:
        body = regenerate(directory, write=not args.dry_run)
        if body is None:
            print(f"WARN: no canonical-frontmatter docs in {directory} — skipped")
            skipped += 1
            continue
        if args.dry_run:
            print(f"--- {directory}/00-index.md ---")
            print(body)
        else:
            print(f"OK: regenerated {directory}/00-index.md")
        written += 1
    print(f"INFO: {written} written, {skipped} skipped")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
