"""Git bootstrap for a freshly scaffolded project — repo, ignore file, baseline
commit, and the human-persona hook bodies.

Every entry point here is fail-open: a missing git binary, absent committer
identity, or OS error is reported to the caller as a WARN-shaped result, never
raised, because a scaffold that produced files must not be undone by a git
detail.
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from cli._init_target import InitTarget
from cli._resources import scripts_dir


@dataclass(frozen=True)
class GitInitResult:
    ran: bool
    skipped_reason: str | None
    error: str | None


def maybe_git_init(target: InitTarget, *, enabled: bool) -> GitInitResult:
    """Run `git init -q` unless disabled or target is nested in git.

    Per plan D7/D21: nested-in-git → skip silently; command failure → WARN
    (caller decides how to surface), not FAIL.
    """
    if not enabled:
        return GitInitResult(ran=False, skipped_reason="--no-git flag", error=None)
    if target.nested_in_git:
        return GitInitResult(ran=False, skipped_reason="nested in existing git repo", error=None)
    if (target.path / ".git").exists():
        return GitInitResult(ran=False, skipped_reason="already a git repo", error=None)
    try:
        proc = subprocess.run(
            ["git", "init", "-q"],
            cwd=str(target.path),
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        return GitInitResult(ran=False, skipped_reason=None, error=str(exc))
    if proc.returncode != 0:
        return GitInitResult(
            ran=False,
            skipped_reason=None,
            error=(proc.stderr or proc.stdout or "non-zero exit").strip(),
        )
    return GitInitResult(ran=True, skipped_reason=None, error=None)


# The coding-os runtime carve-outs that MUST be present even when the project
# already ships a baseline .gitignore (from `_base/scaffold`): the cognitive DB
# + WAL sidecars and the rendered, machine-local adapters never enter history.
# `ensure_gitignore` appends this block to any existing file that lacks it.
_RUNTIME_GITIGNORE_BLOCK = """\
# Databases (runtime — coding-os cognitive DB + WAL sidecars)
*.db
*.db-shm
*.db-wal
*.db.backup-*

# coding-os runtime state — keep only the tracked config files
.coding-os/*
!.coding-os/rag-config.yaml
!.coding-os/domain-config.json
!.coding-os/scrumban-config.yaml

# Rendered agent adapters — regenerated by `cos update`; they hold
# machine-absolute symlink paths that do not survive a clone.
.claude/
.codex/
.mcp.json
"""

# Mirrors the meta-repo .gitignore's runtime-ignore intent, minus the
# meta-specific lines (web/ui build, scaffold un-ignores, golden un-ignores).
CONSUMER_GITIGNORE = (
    """\
# coding-os project .gitignore — generated by `cos init`.

# Python
__pycache__/
*.pyc
*.pyo
.venv/
venv/
*.egg-info/
.mypy_cache/
.pytest_cache/
.ruff_cache/
.coverage
.coverage.*
htmlcov/
coverage.xml

# Node / frontend build output
node_modules/
dist/
build/

# Secrets & environment
.env
.env.*
!.env.example
*.pem
*.key

# Editor / OS noise
.idea/
.vscode/
*.swp
*.swo
.DS_Store
Thumbs.db

# Logs
*.log
changes.log

"""
    + _RUNTIME_GITIGNORE_BLOCK
)

_BASELINE_COMMIT_MESSAGE = "chore: scaffold coding-os project"


def ensure_gitignore(project: Path) -> bool:
    """Write or top up a coding-os `.gitignore`. Idempotent.

    No file → write the full template. A pre-existing file (a user's own, or the
    `_base/scaffold` baseline copied at init) is never rewritten, but the runtime
    carve-outs are appended when absent so the cognitive DB and rendered adapters
    never land in history regardless of the baseline's contents.
    """
    gitignore = project / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(CONSUMER_GITIGNORE, encoding="utf-8")
        return True
    existing = gitignore.read_text(encoding="utf-8")
    if any(line.strip() == ".coding-os/*" for line in existing.splitlines()):
        return False
    separator = "" if existing.endswith("\n") else "\n"
    gitignore.write_text(existing + separator + "\n" + _RUNTIME_GITIGNORE_BLOCK, encoding="utf-8")
    return True


@dataclass(frozen=True)
class InitialCommitResult:
    committed: bool
    skipped_reason: str | None
    error: str | None


def maybe_initial_commit(target: InitTarget, *, enabled: bool) -> InitialCommitResult:
    """Stage the freshly-scaffolded tree and make one baseline commit.

    Runs only when `cos init` itself created the repo (caller passes
    `git and git_result.ran`); a nested / pre-existing repo is left
    untouched so we never sweep a parent project's working tree. Fail-open:
    a missing committer identity falls back to a tool identity so a headless
    / CI consumer still gets a clean baseline; any other failure is reported
    (WARN), never fatal.
    """
    if not enabled:
        return InitialCommitResult(committed=False, skipped_reason="no fresh repo", error=None)
    try:
        add = subprocess.run(
            ["git", "add", "-A"],
            cwd=str(target.path),
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
        if add.returncode != 0:
            return InitialCommitResult(
                committed=False,
                skipped_reason=None,
                error=(add.stderr or add.stdout or "git add failed").strip(),
            )
        commit_args = ["commit", "-q", "-m", _BASELINE_COMMIT_MESSAGE]
        commit = subprocess.run(
            ["git", *commit_args],
            cwd=str(target.path),
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
        if commit.returncode != 0:
            # Most common cause: no user.name/user.email configured. Retry
            # once with a tool identity so the baseline always lands.
            commit = subprocess.run(
                [
                    "git",
                    "-c",
                    "user.name=coding-os",
                    "-c",
                    "user.email=init@coding-os.local",
                    *commit_args,
                ],
                cwd=str(target.path),
                capture_output=True,
                text=True,
                timeout=30,
                check=False,
            )
        if commit.returncode != 0:
            return InitialCommitResult(
                committed=False,
                skipped_reason=None,
                error=(commit.stderr or commit.stdout or "git commit failed").strip(),
            )
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        return InitialCommitResult(committed=False, skipped_reason=None, error=str(exc))
    return InitialCommitResult(committed=True, skipped_reason=None, error=None)


@dataclass(frozen=True)
class GitHooksResult:
    installed: tuple[str, ...]
    skipped_reason: str | None
    error: str | None


def install_consumer_git_hooks(project: Path, *, enabled: bool) -> GitHooksResult:
    """Copy the human-persona git hooks into the fresh repo's .git/hooks.

    The bodies resolve `.claude/.codex` hooks at runtime, so the human
    / Codex-GUI commit path — which bypasses every PreToolUse hook — still gets
    the doc-anchor + commit-message backstop. Never clobbers a user's existing
    hook; fail-open — a missing body / OS error is reported, never fatal.
    """
    if not enabled:
        return GitHooksResult(installed=(), skipped_reason="no fresh repo", error=None)
    hooks_dir = project / ".git" / "hooks"
    if not (project / ".git").is_dir():
        return GitHooksResult(installed=(), skipped_reason="no .git", error=None)
    pairs = (
        ("pre-commit", scripts_dir("_pre_commit_body.sh")),
        ("commit-msg", scripts_dir("_commit_msg_body.sh")),
    )
    installed: list[str] = []
    try:
        hooks_dir.mkdir(parents=True, exist_ok=True)
        for name, src in pairs:
            if not src.is_file():
                return GitHooksResult(
                    installed=tuple(installed),
                    skipped_reason=None,
                    error=f"hook body missing: {src.name}",
                )
            dst = hooks_dir / name
            if dst.exists():
                continue  # never overwrite a user-authored hook
            shutil.copy2(src, dst)
            dst.chmod(0o755)
            installed.append(name)
    except OSError as exc:
        return GitHooksResult(installed=tuple(installed), skipped_reason=None, error=str(exc))
    return GitHooksResult(installed=tuple(installed), skipped_reason=None, error=None)
