"""Render .github/workflows/ci.yml from the aggregated verify rows.

The language→toolchain tables change when GitHub Actions moves, which is a
different clock from the fragment templates or the Docker skeletons. They are
the only reason this module exists, so they live alone with their one consumer.
"""

from __future__ import annotations

import logging
import re

from cli._data_types import AggregatedWorld

logger = logging.getLogger(__name__)

# File extension a verify-row glob ends with → language. Languages are the gate
# for which toolchain CI installs; the row owns one stack root, hence one match.
_EXT_LANGUAGE: dict[str, str] = {
    "py": "python",
    "ts": "typescript",
    "tsx": "typescript",
    "js": "typescript",
    "jsx": "typescript",
    "go": "go",
    "php": "php",
    "rs": "rust",
    "rb": "ruby",
    "java": "java",
    "kt": "java",
    "cs": "csharp",
    "dart": "dart",
}

# Language → GitHub Actions toolchain setup step(s). Pinned to the runtime only,
# never the lint/test tools — those stay in `make`, so this never rots when a
# framework version moves. A language with no entry runs make against whatever
# the runner preinstalls (best effort).
_CI_LANGUAGE_SETUP: dict[str, tuple[str, ...]] = {
    "python": (
        "uses: actions/setup-python@v5",
        "with:",
        '  python-version: "3.12"',
    ),
    "typescript": (
        "uses: actions/setup-node@v4",
        "with:",
        '  node-version: "22"',
    ),
    "go": (
        "uses: actions/setup-go@v5",
        "with:",
        '  go-version: "stable"',
    ),
    "php": (
        "uses: shivammathur/setup-php@v2",
        "with:",
        '  php-version: "8.2"',
    ),
    "rust": ("uses: dtolnay/rust-toolchain@stable",),
    "ruby": (
        "uses: ruby/setup-ruby@v1",
        "with:",
        '  ruby-version: "3.3"',
    ),
    "java": (
        "uses: actions/setup-java@v4",
        "with:",
        '  distribution: "temurin"',
        '  java-version: "21"',
    ),
    "csharp": (
        "uses: actions/setup-dotnet@v4",
        "with:",
        '  dotnet-version: "8.0"',
    ),
    "dart": ("uses: dart-lang/setup-dart@v1",),
}

# Language → per-stack-root dependency install. Mirrors the bootable manifests
# pyproject `[test]` extras, package.json, go.mod, composer.json.
_CI_LANGUAGE_INSTALL: dict[str, str] = {
    "python": "pip install -e '.[test]'",
    "typescript": "npm install",
    "go": "go mod download",
    "php": "composer install",
    "ruby": "bundle install",
    "rust": "cargo fetch",
    "java": "./mvnw -q -B dependency:go-offline",
    "csharp": "dotnet restore",
    "dart": "dart pub get",
}


def language_for_glob(glob: str) -> str:
    tail = glob.rsplit("/", 1)[-1]
    if "." not in tail:
        return ""
    for ext in re.findall(r"[A-Za-z0-9]+", tail.split(".", 1)[-1]):
        if ext in _EXT_LANGUAGE:
            return _EXT_LANGUAGE[ext]
    return ""


def render_ci_workflow(world: AggregatedWorld) -> str:
    """Emit a single .github/workflows/ci.yml — the structural twin of
    render_makefile_targets.

    Consumer-owned (written once at init, not a live symlink). One matrix leg
    per language, each running that language's generated make targets, so the
    body delegates to `make` and never rots with tool versions; re-rendering
    after a stack is added picks up its targets automatically. macOS is kept
    off the per-push path — those runners bill at 10x.
    """
    runnable = {t.name for t in world.makefile_targets}
    targets_by_language: dict[str, list[str]] = {}
    roots_by_language: dict[str, list[str]] = {}
    for row in world.verify_rows:
        language = language_for_glob(row.glob)
        if not language:
            continue
        for suite in row.suites.split("+"):
            name = suite.strip()
            if name in runnable and name not in targets_by_language.setdefault(language, []):
                targets_by_language.setdefault(language, []).append(name)
        if "/**" in row.glob:
            root = row.glob.split("/**", 1)[0].rstrip("/")
            if root and root not in roots_by_language.setdefault(language, []):
                roots_by_language[language].append(root)

    languages = [lang for lang in targets_by_language if targets_by_language[lang]]
    if not languages:
        return ""

    lines: list[str] = [
        "# Auto-generated by coding-os `cos init` — consumer-owned (edit freely; not a symlink).",
        "# Body delegates to the generated make targets so it never rots with tool",
        "# versions; adding a stack re-renders this with the new targets.",
        "name: CI",
        "on:",
        "  push:",
        "    branches: [main]",
        '    paths-ignore: ["docs/tasks/**"]',
        "  pull_request:",
        "    branches: [main]",
        "  workflow_dispatch:",
        "concurrency:",
        "  group: ci-${{ github.workflow }}-${{ github.ref }}",
        "  cancel-in-progress: ${{ github.event_name == 'pull_request' }}",
        "permissions:",
        "  contents: read",
        "jobs:",
        "  verify:",
        "    name: verify (${{ matrix.language }})",
        # macOS runners bill at 10x — never on the per-push path (nightly elsewhere if needed).
        "    runs-on: ubuntu-latest",
        "    strategy:",
        "      fail-fast: false",
        "      matrix:",
        "        include:",
    ]
    for lang in languages:
        lines.append(f"          - language: {lang}")
        lines.append(f'            targets: "{" ".join(targets_by_language[lang])}"')
    lines.append("    steps:")
    lines.append("      - uses: actions/checkout@v4")
    for lang in languages:
        guard = f"        if: matrix.language == '{lang}'"
        for index, step_line in enumerate(_CI_LANGUAGE_SETUP.get(lang, ())):
            prefix = "      - " if index == 0 else "        "
            lines.append(prefix + step_line)
            if index == 0:
                lines.append(guard)
        install = _CI_LANGUAGE_INSTALL.get(lang)
        if install:
            lines.append(f"      - name: deps ({lang})")
            lines.append(guard)
            lines.append("        run: |")
            for root in roots_by_language.get(lang, []):
                lines.append(f"          (cd {root} && {install})")
    lines.append("      - name: verify")
    lines.append("        run: make ${{ matrix.targets }}")
    # Documented seam for an image/dependency scanner (Trivy, Grype, …). Left
    # commented: the scanner is an agent skill, not generated machinery (Rule 22).
    lines.append("  # security-scan:")
    lines.append("  #   runs-on: ubuntu-latest")
    lines.append("  #   steps:")
    lines.append("  #     - uses: actions/checkout@v4")
    lines.append("  #     - run: echo 'wire an image/dependency scanner here'")
    return "\n".join(lines) + "\n"
