"""Per-language Dockerfile skeletons and the .dockerignore beside them.

Base images and their idioms move on the upstream registries' clock, not the
project's; keeping them here means bumping a base image never opens the module
that composes AGENTS.md. Pure data plus two lookups — no world required.
"""

from __future__ import annotations

# Per-language multi-stage, non-root, healthchecked Dockerfile skeleton. Keyed by
# the backend stack's language base image (TASK-610). A skeleton, not a finished
# image: the CMD/healthcheck target is the seam a consumer adjusts to its
# entrypoint. Only category=backend stacks get one — see materialize_dockerfiles.
_DOCKERFILE_SKELETONS: dict[str, str] = {
    "python": """\
# syntax=docker/dockerfile:1
FROM python:3.12-slim AS build
WORKDIR /app
COPY pyproject.toml ./
RUN pip install --no-cache-dir --prefix=/install .

FROM python:3.12-slim AS runtime
WORKDIR /app
COPY --from=build /install /usr/local
COPY . .
RUN useradd --create-home appuser && chown -R appuser /app
USER appuser
EXPOSE 8000
HEALTHCHECK CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')" || exit 1
# Adjust to your entrypoint (e.g. gunicorn config.wsgi / uvicorn app.main:app).
CMD ["python", "-m", "app.main"]
""",
    "typescript": """\
# syntax=docker/dockerfile:1
FROM node:22-slim AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build --if-present

FROM node:22-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app ./
USER node
EXPOSE 3000
HEALTHCHECK CMD node -e "fetch('http://localhost:3000/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"
CMD ["npm", "start"]
""",
    "go": """\
# syntax=docker/dockerfile:1
FROM golang:1.22 AS build
WORKDIR /src
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/server ./...

FROM gcr.io/distroless/static-debian12 AS runtime
COPY --from=build /out/server /server
USER nonroot:nonroot
EXPOSE 8080
# Distroless has no shell — wire a /health probe at the orchestrator (k8s livenessProbe).
CMD ["/server"]
""",
    "php": """\
# syntax=docker/dockerfile:1
FROM composer:2 AS build
WORKDIR /app
COPY composer.json ./
RUN composer install --no-dev --no-interaction --no-scripts

FROM php:8.2-fpm-alpine AS runtime
WORKDIR /app
COPY --from=build /app/vendor ./vendor
COPY . .
USER www-data
EXPOSE 9000
HEALTHCHECK CMD php -r "exit(0);" || exit 1
CMD ["php-fpm"]
""",
    "java": """\
# syntax=docker/dockerfile:1
FROM eclipse-temurin:21-jdk AS build
WORKDIR /app
COPY . .
RUN ./mvnw -q package -DskipTests

FROM eclipse-temurin:21-jre AS runtime
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
RUN useradd appuser
USER appuser
EXPOSE 8080
HEALTHCHECK CMD wget -qO- http://localhost:8080/actuator/health || exit 1
CMD ["java", "-jar", "app.jar"]
""",
    "csharp": """\
# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app ./
USER $APP_UID
EXPOSE 8080
# Wire ASP.NET health checks (app.MapHealthChecks("/health")) then probe here.
CMD ["dotnet", "app.dll"]
""",
    "ruby": """\
# syntax=docker/dockerfile:1
FROM ruby:3.3-slim AS build
WORKDIR /app
COPY Gemfile* ./
RUN bundle install --without development test

FROM ruby:3.3-slim AS runtime
WORKDIR /app
COPY --from=build /usr/local/bundle /usr/local/bundle
COPY . .
RUN useradd appuser && chown -R appuser /app
USER appuser
EXPOSE 3000
HEALTHCHECK CMD ruby -rnet/http -e "Net::HTTP.get(URI('http://localhost:3000/health'))" || exit 1
# Adjust to your entrypoint (rails: bin/rails server -b 0.0.0.0; rack: rackup).
CMD ["ruby", "app.rb"]
""",
    "rust": """\
# syntax=docker/dockerfile:1
FROM rust:1 AS build
WORKDIR /src
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim AS runtime
WORKDIR /app
COPY --from=build /src/target/release/app /usr/local/bin/app
RUN useradd appuser
USER appuser
EXPOSE 8080
HEALTHCHECK CMD /usr/local/bin/app --health || exit 1
CMD ["app"]
""",
}

_DOCKERIGNORE = """\
# Auto-generated by coding-os `cos init` — consumer-owned.
.git
.gitignore
**/.coding-os
**/node_modules
**/__pycache__
**/.venv
**/target
**/dist
**/*.log
**/.env
**/.env.*
Dockerfile
.dockerignore
"""


def render_dockerfile(language: str) -> str:
    """Multi-stage, non-root Dockerfile skeleton for a backend language, or "".

    The build stage carries the toolchain, the runtime stage only the artifact;
    the runtime runs as a non-root user with a healthcheck. Returns "" for a
    language with no skeleton (frontend/mobile/library never get one).
    """
    return _DOCKERFILE_SKELETONS.get(language, "")


def render_dockerignore() -> str:
    """The .dockerignore shipped beside a generated Dockerfile."""
    return _DOCKERIGNORE
