"""Compose per-stack `.coding-os/` configs at `cos init`.

Base defaults are deep-merged with each installed stack's overlay, data-driven
(iterates the `templates` list — Rule 11) and multi-stack-correct. Idempotent:
never clobbers an existing target. SSOT: docs/engineering/config-composition.md.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path
from typing import Any

import click
import yaml

# Per-file merge spec: top-level key → strategy. Strategies:
#   "union_by:<key>"  list of dicts, union by <key> (later wins on collision)
#   "union_list"      list of scalars, order-preserving dedupe
#   "dict_merge"      recursive: dicts merge, nested lists union, scalars override
#   "override"        later value wins wholesale
# A key present in an overlay but absent from the spec defaults to "override".
RAG_SPEC: dict[str, str] = {
    "sources": "union_by:path",
    "exclude": "union_list",
    "graph": "dict_merge",
}
SCRUMBAN_SPEC: dict[str, str] = {
    "swimlanes": "union_by:id",
    "wip_limits": "dict_merge",
    "workflow_policy": "dict_merge",
    "label_families": "union_by:name",
}
DOMAIN_SPEC: dict[str, str] = {
    "refs_by_tag": "dict_merge",
    "domain_map": "dict_merge",
    "playbook_map": "dict_merge",
    "default_refs": "override",
    "default_domain": "override",
    "default_playbook": "override",
}

# (filename, spec, format) for each composed config.
_COMPOSED: tuple[tuple[str, dict[str, str], str], ...] = (
    ("rag-config.yaml", RAG_SPEC, "yaml"),
    ("scrumban-config.yaml", SCRUMBAN_SPEC, "yaml"),
    ("domain-config.json", DOMAIN_SPEC, "json"),
)

# Filenames excluded from `_overlay_scaffold` so they don't shadow the composed
# output (first-writer-wins). Kept here as the single source.
COMPOSED_FILENAMES: frozenset[str] = frozenset(name for name, _, _ in _COMPOSED)


def _union_list(base: list[Any], overlay: list[Any]) -> list[Any]:
    out: list[Any] = []
    seen: set[str] = set()
    for item in [*base, *overlay]:
        marker = item if isinstance(item, str) else json.dumps(item, sort_keys=True)
        if marker in seen:
            continue
        seen.add(marker)
        out.append(item)
    return out


def _union_by_key(base: list[Any], overlay: list[Any], key: str) -> list[Any]:
    out = [copy.deepcopy(item) for item in base]
    index = {item.get(key): i for i, item in enumerate(out) if isinstance(item, dict)}
    for item in overlay:
        if isinstance(item, dict) and item.get(key) in index:
            out[index[item[key]]] = copy.deepcopy(item)  # later wins on collision
        else:
            if isinstance(item, dict):
                index[item.get(key)] = len(out)
            out.append(copy.deepcopy(item))
    return out


def _deep_merge(base: Any, overlay: Any) -> Any:
    if isinstance(base, dict) and isinstance(overlay, dict):
        out = copy.deepcopy(base)
        for k, v in overlay.items():
            out[k] = _deep_merge(out[k], v) if k in out else copy.deepcopy(v)
        return out
    if isinstance(base, list) and isinstance(overlay, list):
        return _union_list(base, overlay)
    return copy.deepcopy(overlay)


def _merge_value(base_val: Any, overlay_val: Any, strategy: str) -> Any:
    if overlay_val is None:
        return base_val
    if strategy == "union_list":
        return _union_list(base_val or [], overlay_val or [])
    if strategy == "override":
        return copy.deepcopy(overlay_val)
    if strategy == "dict_merge":
        return _deep_merge(base_val or {}, overlay_val)
    if strategy.startswith("union_by:"):
        return _union_by_key(base_val or [], overlay_val or [], strategy.split(":", 1)[1])
    raise ValueError(f"unknown merge strategy: {strategy!r}")


def compose(base: dict[str, Any], overlays: list[dict[str, Any]], spec: dict[str, str]) -> dict[str, Any]:
    """Deep-merge `base` with each overlay in order per the strategy `spec`."""
    result = copy.deepcopy(base)
    for overlay in overlays:
        if not isinstance(overlay, dict):
            continue
        for key in [*spec, *(k for k in overlay if k not in spec)]:
            if key not in overlay:
                continue
            result[key] = _merge_value(result.get(key), overlay[key], spec.get(key, "override"))
    return result


def _load(path: Path, fmt: str) -> dict[str, Any] | None:
    if not path.is_file():
        return None
    text = path.read_text(encoding="utf-8")
    try:
        data = json.loads(text) if fmt == "json" else yaml.safe_load(text)
    except (yaml.YAMLError, json.JSONDecodeError) as exc:
        raise click.ClickException(f"{path} is not valid {fmt.upper()}: {exc}") from exc
    return data if isinstance(data, dict) else None


_YAML_HEADER = (
    "# GENERATED by `cos init` — composed from base defaults + every installed\n"
    "# stack. Edit freely: init/update never clobbers an existing file. Schema +\n"
    "# merge rules: docs/engineering/config-composition.md\n\n"
)


def _dump(data: dict[str, Any], fmt: str) -> str:
    if fmt == "json":
        return json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    body = yaml.safe_dump(data, sort_keys=False, default_flow_style=False, allow_unicode=True)
    return _YAML_HEADER + body


def compose_coding_os_configs(
    project: Path,
    state: Path,
    templates: list[str],
    *,
    templates_dir: Path,
) -> list[str]:
    """Compose `.coding-os/` configs from base + installed stacks. Returns written names."""
    written: list[str] = []
    base_dir = templates_dir / "_base" / "scaffold" / ".coding-os"
    for filename, spec, fmt in _COMPOSED:
        target = state / filename
        if target.exists():
            continue  # idempotent — never clobber a user / prior-run file
        base = _load(base_dir / filename, fmt)
        overlays: list[dict[str, Any]] = []
        for stack_id in templates:
            overlay = _load(templates_dir / stack_id / "scaffold" / ".coding-os" / filename, fmt)
            if overlay is not None:
                overlays.append(overlay)
        if base is None and not overlays:
            continue
        merged = compose(base or {}, overlays, spec)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_dump(merged, fmt), encoding="utf-8")
        written.append(filename)
    return written


def recompose_for_added_stack(
    project: Path,
    state: Path,
    stack_id: str,
    *,
    templates_dir: Path,
) -> list[str]:
    """Merge a newly-added stack's `.coding-os/` overlay onto the existing configs.

    Merges onto the CURRENT composed file (not a fresh base) so user edits and
    prior stacks are preserved; re-adding the same stack is a no-op (union
    dedupes). Used by `cos add-stack`. SSOT: docs/engineering/config-composition.md.
    """
    written: list[str] = []
    base_dir = templates_dir / "_base" / "scaffold" / ".coding-os"
    for filename, spec, fmt in _COMPOSED:
        overlay = _load(templates_dir / stack_id / "scaffold" / ".coding-os" / filename, fmt)
        if overlay is None:
            continue
        target = state / filename
        existing = _load(target, fmt)
        base = existing if existing is not None else (_load(base_dir / filename, fmt) or {})
        merged = compose(base, [overlay], spec)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_dump(merged, fmt), encoding="utf-8")
        written.append(filename)
    return written


def recompose_for_removed_stack(
    project: Path,
    state: Path,
    remaining_templates: list[str],
    *,
    templates_dir: Path,
) -> list[str]:
    """Rebuild the composed `.coding-os/` configs from base + the REMAINING stacks.

    A merged config cannot be un-merged for a single stack (union strategies are
    lossy), so removal recomposes each file fresh from the base defaults plus
    every still-installed stack's overlay — dropping the removed stack's
    contribution. Used by `cos remove-stack`; the caller backs up the targets
    first because this DISCARDS any user edits layered onto the composed files.
    A file is rewritten only when the recompose differs from the current target,
    so the operation is diff-minimal and idempotent. SSOT:
    docs/engineering/config-composition.md.
    """
    written: list[str] = []
    base_dir = templates_dir / "_base" / "scaffold" / ".coding-os"
    for filename, spec, fmt in _COMPOSED:
        target = state / filename
        if not target.is_file():
            continue  # nothing composed here — nothing to rebuild
        base = _load(base_dir / filename, fmt)
        overlays: list[dict[str, Any]] = []
        for stack_id in remaining_templates:
            overlay = _load(templates_dir / stack_id / "scaffold" / ".coding-os" / filename, fmt)
            if overlay is not None:
                overlays.append(overlay)
        merged = compose(base or {}, overlays, spec)
        new_text = _dump(merged, fmt)
        if target.read_text(encoding="utf-8") == new_text:
            continue  # recompose is a no-op for this file
        target.write_text(new_text, encoding="utf-8")
        written.append(filename)
    return written
