"""Render AggregatedWorld into concrete project artifacts.

Pure except for fragment file reads. Every renderer takes the world
(and maybe an adapter profile) and returns a string or dict ready to
be written.

The single most important contract: **NO literal markdown template
lives in this file**. Every piece of AGENTS.md or any other generated
doc comes from a fragment file declared in base.yaml or stack.yaml.
To add a new section, create a fragment and register it — do not
touch this module.

AGENTS.md composition, the CI workflow, and the Docker skeletons moved to leaf
siblings — each moves on a different clock (fragments, GitHub Actions, base
images). Every name they own is re-exported here, so `from cli.renderer import
…` keeps resolving.
"""

from __future__ import annotations

import logging
from copy import deepcopy

from cli._data_types import AdapterProfile, AggregatedWorld, HookEntry
from cli._render_agents_md import (
    _disabled_module_skills as _disabled_module_skills,
    _gate_installed_skills as _gate_installed_skills,
    _make_env as _make_env,
    _modules_context as _modules_context,
    _world_to_context as _world_to_context,
    render_agents_md as render_agents_md,
)
from cli._render_ci import (
    _CI_LANGUAGE_INSTALL as _CI_LANGUAGE_INSTALL,
    _CI_LANGUAGE_SETUP as _CI_LANGUAGE_SETUP,
    _EXT_LANGUAGE as _EXT_LANGUAGE,
    language_for_glob as language_for_glob,
    render_ci_workflow as render_ci_workflow,
)
from cli._render_docker import (
    _DOCKERFILE_SKELETONS as _DOCKERFILE_SKELETONS,
    _DOCKERIGNORE as _DOCKERIGNORE,
    render_dockerfile as render_dockerfile,
    render_dockerignore as render_dockerignore,
)
from cli._render_errors import RenderError as RenderError

logger = logging.getLogger(__name__)


def _hook_to_settings_entry(hook: HookEntry) -> dict:
    """Convert a HookEntry into the shape .claude/settings.json expects."""
    return {
        "matcher": hook.matcher,
        "hooks": [{"type": "command", "command": hook.command}],
    }


def render_settings_json(world: AggregatedWorld, adapter: AdapterProfile) -> dict:
    """Deep-merge adapter defaults with aggregated hooks.

    Returns {} if the adapter doesn't support settings.json — the caller
    is expected to skip writing the file in that case.
    """
    if not adapter.supports_settings_json:
        logger.debug(
            "adapter %s does not support settings.json, render_settings_json returns {}",
            adapter.id,
        )
        return {}

    result = deepcopy(adapter.default_settings)
    result.setdefault("hooks", {})
    hooks_section = result["hooks"]
    if not isinstance(hooks_section, dict):
        raise RenderError(f"adapter {adapter.id} default_settings.hooks must be a mapping")

    # Group aggregated hooks by event.
    by_event: dict[str, list[HookEntry]] = {}
    for h in world.hooks:
        by_event.setdefault(h.event, []).append(h)

    for event, hook_list in by_event.items():
        hooks_section.setdefault(event, [])
        if not isinstance(hooks_section[event], list):
            raise RenderError(f"adapter {adapter.id} default_settings.hooks.{event} must be a list")
        hooks_section[event].extend(_hook_to_settings_entry(h) for h in hook_list)

    return result


def render_makefile_targets(world: AggregatedWorld) -> str:
    """Produce a Makefile fragment with one target per aggregated entry.

    Designed to be written to <project>/.coding-os/Makefile.stacks and
    pulled into the project Makefile via `-include .coding-os/Makefile.stacks`.
    """
    if not world.makefile_targets:
        return "# No stack-contributed Makefile targets.\n"

    lines: list[str] = [
        "# Auto-generated by coding-os — do not edit by hand.",
        "# Regenerated every time `cos init` or `cos add-stack` runs.",
        "",
    ]
    phony = " ".join(t.name for t in world.makefile_targets)
    lines.append(f".PHONY: {phony}")
    lines.append("")
    for target in world.makefile_targets:
        if target.help:
            lines.append(f"{target.name}:  ## {target.help}")
        else:
            lines.append(f"{target.name}:")
        lines.append(f"\t{target.cmd}")
        lines.append("")
    return "\n".join(lines)


def render_dimension_registry(world: AggregatedWorld) -> str:
    """Aggregate dimension entries into a markdown doc grouped by stack."""
    lines: list[str] = [
        "# Dimension Registry",
        "",
        "Auto-generated from all installed stacks. Use during Classify",
        "phase to build your Read List.",
        "",
    ]
    if not world.dimensions:
        lines.append("_No dimensions contributed by any stack._")
        lines.append("")
        return "\n".join(lines)

    by_stack: dict[str, list] = {}
    for d in world.dimensions:
        by_stack.setdefault(d.stack_id, []).append(d)

    for stack_id in sorted(by_stack):
        lines.append(f"## {stack_id}")
        lines.append("")
        for dim in by_stack[stack_id]:
            files_fmt = ", ".join(f"`{f}`" for f in dim.read_files)
            lines.append(f"- **{dim.name}** ({dim.depth}) → {files_fmt}")
        lines.append("")
    return "\n".join(lines)


def render_skill_enforcement(world: AggregatedWorld) -> str:
    """Aggregate skill_enforcement entries into a markdown doc."""
    lines: list[str] = [
        "# Skill Enforcement",
        "",
        "Auto-generated. Before writing code matching any glob below,",
        "invoke the matching skill via the `Skill` tool.",
        "",
        "| Globs | Primary Skill | Secondary Skills | Stack |",
        "| --- | --- | --- | --- |",
    ]
    if not world.skill_enforcement:
        lines.append("| _none_ | _none_ | _none_ | _none_ |")
        lines.append("")
        return "\n".join(lines)

    for se in world.skill_enforcement:
        globs_fmt = ", ".join(f"`{g}`" for g in se.globs)
        secondary_fmt = ", ".join(se.secondary) if se.secondary else "—"
        lines.append(f"| {globs_fmt} | `{se.primary}` | {secondary_fmt} | {se.stack_id} |")
    lines.append("")
    return "\n".join(lines)
