#!/usr/bin/env python3
"""Repo-wide backstop for the file-size budget (anti-overengineering.md sub-rule 6).

The PreToolUse hook stops an agent authoring an oversized file; this stops one
arriving any other way — a human commit, a generator, a merge. `cos doctor` and
the Hub import `scan()` directly rather than shelling out, so the thresholds and
the exemption list have exactly one definition.

    python3 check_file_size.py [path ...]   # defaults to the whole repo
    python3 check_file_size.py --json       # machine-readable, for agents
    COS_MAX_FILE_LINES=300 python3 check_file_size.py

Exit 1 when any file is over the ceiling; warnings alone still exit 0.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

DEFAULT_CEILING = 500
DEFAULT_WARN_AT = 400

SOURCE_SUFFIXES = frozenset(
    {
        ".py",
        ".ts",
        ".tsx",
        ".js",
        ".jsx",
        ".go",
        ".rs",
        ".rb",
        ".php",
        ".java",
        ".cs",
        ".dart",
        ".sh",
    }
)

# Generated, vendored, or downstream-owned: the backstop counts hand-written
# reasons to change, not lines. Kept in sync with block-bad-patterns.sh.
EXCLUDED_PARTS = frozenset(
    {
        "node_modules",
        "__pycache__",
        "dist",
        "build",
        "vendor",
        "migrations",
        "scaffold",
        "golden",
        ".venv",
        ".git",
        ".build",
        "archive",
        # Agent/state dirs in a consumer project are symlinks back into the
        # coding-os install — walking them would blame the consumer for the
        # kernel's files.
        ".coding-os",
        ".claude",
        ".codex",
    }
)


def thresholds() -> tuple[int, int]:
    def _read(name: str, default: int) -> int:
        try:
            return int(os.environ.get(name) or default)
        except ValueError:
            return default

    return (
        _read("COS_MAX_FILE_LINES", DEFAULT_CEILING),
        _read("COS_WARN_FILE_LINES", DEFAULT_WARN_AT),
    )


def _candidates(roots: list[str], repo_root: Path) -> list[Path]:
    try:
        out = subprocess.run(
            ["git", "ls-files", "--", *roots],
            cwd=repo_root,
            capture_output=True,
            text=True,
            check=True,
            timeout=60,
        )
        return [repo_root / line for line in out.stdout.splitlines() if line]
    except (OSError, subprocess.SubprocessError):
        # Not a git tree. Skip symlinks: a consumer project links whole
        # directories back into the coding-os install.
        return [p for root in roots for p in (repo_root / root).rglob("*") if not p.is_symlink()]


# Conventional machine-generated banners. A generated file has no hand-written
# reasons to change, so the budget does not apply to it.
GENERATED_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "do not edit",
    "do not make direct changes",
    "code generated by",
)
_GENERATED_SCAN_BYTES = 2048


def _is_generated(path: Path) -> bool:
    try:
        with path.open("rb") as handle:
            head = handle.read(_GENERATED_SCAN_BYTES).decode("utf-8", "ignore").lower()
    except OSError:
        return False
    return any(marker in head for marker in GENERATED_MARKERS)


def _is_source(path: Path) -> bool:
    if path.suffix not in SOURCE_SUFFIXES:
        return False
    if EXCLUDED_PARTS.intersection(path.parts):
        return False
    return not _is_generated(path)


def _line_count(path: Path) -> int | None:
    try:
        with path.open("rb") as handle:
            return sum(1 for _ in handle)
    except OSError:
        return None


def scan(
    roots: list[str] | None = None,
    repo_root: Path | None = None,
    ceiling: int | None = None,
    warn_at: int | None = None,
) -> dict:
    """Return the file-size verdict as a plain dict — the shape doctor + Hub read."""
    env_ceiling, env_warn = thresholds()
    ceiling = env_ceiling if ceiling is None else ceiling
    warn_at = env_warn if warn_at is None else warn_at
    root = (repo_root or Path.cwd()).resolve()

    violations: list[dict] = []
    for path in _candidates(roots or ["."], root):
        if not _is_source(path) or not path.is_file():
            continue
        lines = _line_count(path)
        if lines is None:
            continue
        if lines > ceiling:
            tier = "error"
        elif lines > warn_at:
            tier = "warn"
        else:
            continue
        try:
            name = str(path.relative_to(root))
        except ValueError:
            name = str(path)
        violations.append({"file": name, "lines": lines, "tier": tier})

    violations.sort(key=lambda item: -item["lines"])
    errors = [v for v in violations if v["tier"] == "error"]
    return {
        "ok": not errors,
        "ceiling": ceiling,
        "warn_at": warn_at,
        "error_count": len(errors),
        "warn_count": len(violations) - len(errors),
        "violations": violations,
    }


def _print_human(result: dict) -> None:
    warnings = [v for v in result["violations"] if v["tier"] == "warn"]
    errors = [v for v in result["violations"] if v["tier"] == "error"]

    if warnings:
        print(
            f"WARN: {len(warnings)} file(s) past {result['warn_at']} lines — "
            "find the extraction seam before adding behavior:",
            file=sys.stderr,
        )
        for item in warnings:
            print(f"  {item['file']}: {item['lines']} lines", file=sys.stderr)

    if errors:
        print(
            f"ERROR: {len(errors)} file(s) over the {result['ceiling']}-line backstop — "
            "split along an existing seam:",
            file=sys.stderr,
        )
        for item in errors:
            print(f"  {item['file']}: {item['lines']} lines", file=sys.stderr)
        print(
            "Splitting to hit a number is not the goal: each extracted module must own\n"
            "a coherent responsibility. Rationale: anti-overengineering.md sub-rule 6,\n"
            "clean-code skill § File Design.",
            file=sys.stderr,
        )
        return

    print(f"OK: no source file exceeds {result['ceiling']} lines")


def main(argv: list[str]) -> int:
    roots = [arg for arg in argv if not arg.startswith("--")] or ["."]
    result = scan(roots)
    if "--json" in argv:
        print(json.dumps(result))
    else:
        _print_human(result)
    return 1 if result["error_count"] else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
