#!/usr/bin/env bash
# Mark a task as blocked: update docs/tasks.md, log question in docs/_meta/questions.md.
# Usage: task-block.sh <TASK> <REASON>
set -euo pipefail
source "$(dirname "$0")/_lib.sh"

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  echo "Usage: $0 <TASK> <REASON>"
  echo ""
  echo "Mark a task as blocked and log the blocker question."
  echo ""
  echo "Arguments:"
  echo "  TASK    Task number or ID (e.g. 14, 014, TASK-14, TASK-014)"
  echo "  REASON  Why the task is blocked (quoted string)"
  echo ""
  echo "Steps performed:"
  echo "  1. Validate task exists in docs/tasks.md"
  echo "  2. Verify task is open [ ] or in-progress [/] (refuse if already done or blocked)"
  echo "  3. Change checkbox to (BLOCKED: reason) in docs/tasks.md"
  echo "  4. Append blocker question to docs/_meta/questions.md"
  echo "  5. Print confirmation"
  echo ""
  echo "Example:"
  echo "  make task-block TASK=024 REASON=\"Facebook OAuth developer account not created\""
  exit 0
fi

RAW_TASK="${1:-${TASK:-}}"
REASON="${2:-${REASON:-}}"

if [ -z "$RAW_TASK" ] || [ -z "$REASON" ]; then
  echo "Usage: $0 <TASK> <REASON>"
  echo "Both TASK and REASON are required."
  exit 1
fi

echo "=== task-block ==="

python3 - "$RAW_TASK" "$REASON" <<'PY'
from pathlib import Path
from datetime import date
import re
import sys

raw_task = sys.argv[1]
reason = sys.argv[2]

match = re.fullmatch(r"(?:TASK-?)?(\d+)", raw_task)
if not match:
    raise SystemExit("ERROR: Invalid task format. Use: 14, 014, TASK-14, or TASK-014")

task_num = int(match.group(1))
padded = f"{task_num:03d}"
task_id = f"TASK-{padded}"
today = date.today().isoformat()

# --- Update docs/tasks.md ---
index_path = Path("docs/tasks.md")
if not index_path.exists():
    raise SystemExit(f"ERROR: Task list not found: {index_path}")

index_text = index_path.read_text()
lines = index_text.splitlines()

# Match only checkbox lines, not dependency references like "(depends: TASK-070)"
task_pattern = re.compile(rf"^- \[.\] {re.escape(task_id)}:|^- \(BLOCKED:.*{re.escape(task_id)}")
task_line_idx = None
for i, line in enumerate(lines):
    if task_pattern.match(line.strip()):
        task_line_idx = i
        break

if task_line_idx is None:
    raise SystemExit(f"ERROR: {task_id} not found in {index_path}")

task_line = lines[task_line_idx].strip()

if task_line.startswith("- [x]"):
    raise SystemExit(f"ERROR: {task_id} is already done. Cannot block a completed task.")
if task_line.startswith("- (BLOCKED:"):
    print(f"{task_id} is already blocked.")
    sys.exit(0)

# Extract title
title_match = re.search(rf"{re.escape(task_id)}:\s*(.+)$", task_line)
title = title_match.group(1).strip() if title_match else task_id

# Replace checkbox with BLOCKED marker
old_line = lines[task_line_idx]
# Remove the checkbox prefix and rebuild with BLOCKED
stripped_title = re.sub(r"^-\s*\[.\]\s*", "", old_line.strip())
new_line = f"- (BLOCKED: {reason}) {stripped_title}"
lines[task_line_idx] = new_line

index_path.write_text("\n".join(lines) + "\n")
print(f"Marked {task_id} as BLOCKED in docs/tasks.md")

# --- Log to docs/_meta/questions.md ---
questions_path = Path("docs/_meta/questions.md")
if questions_path.exists():
    q_text = questions_path.read_text()
else:
    q_text = "<!-- domain:ALL | layer:reference | ssot:true | updated:" + today + " -->\n# Open Questions\n\n"

# Find next Q number
q_numbers = re.findall(r"### Q-(\d{3})", q_text)
next_q = max((int(n) for n in q_numbers), default=0) + 1
q_id = f"Q-{next_q:03d}"

# Append question entry (matches Entry Template format in questions.md)
entry = f"""
### {q_id} — {reason[:60]}

- Date: {today}
- Task: {task_id}
- Status: OPEN
- Question: {reason}
- Why this blocks progress: Cannot continue {task_id} without resolution.
- Checked files: (auto-generated by task-block)
- Proposed safe default (if any):
- Final decision:
"""

q_text = q_text.rstrip() + "\n" + entry
questions_path.write_text(q_text)
print(f"Logged blocker as {q_id} in docs/_meta/questions.md")

print(f"\nBlocked: {task_id} — {title}")
print(f"Reason: {reason}")
PY
