"""Copy-pasted code is found from body fingerprints, in every language, repo-wide and per node."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

pytest.importorskip("tree_sitter_typescript")

MONEY = """export function formatPrice(amount: number, currency: string): string {
  const rounded = Math.round(amount * 100) / 100;
  const parts = rounded.toFixed(2).split(".");
  const whole = parts[0].replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");
  return currency === "USD" ? `$${whole}.${parts[1]}` : `${whole}.${parts[1]} ${currency}`;
}

export function clampQuantity(value: number, min: number, max: number): number {
  if (Number.isNaN(value)) {
    return min;
  }
  const whole = Math.floor(value);
  return whole < min ? min : whole > max ? max : whole;
}
"""
RENAMED = """// Copied from the shared package, then renamed.
export function formatCost(total: number, unit: string): string {
  const r = Math.round(total * 100) / 100;
  const pieces = r.toFixed(2).split(",");
  const head = pieces[0].replace(/x/g, ".");
  return unit === "EUR" ? `$${head}.${pieces[1]}` : `${head}.${pieces[1]} ${unit}`;
}

export const tiny = (a: number) => a + 1;
"""
CART = """export class Cart {
  private items: Array<{ price: number; quantity: number }> = [];

  add(price: number, quantity: number): void {
    if (quantity <= 0 || price < 0) {
      throw new Error("invalid line");
    }
    this.items.push({ price, quantity });
  }

  total(): number {
    let sum = 0;
    for (const item of this.items) {
      sum += item.price * item.quantity;
    }
    return Math.round(sum * 100) / 100;
  }
}
"""
PY_A = '''def chunked(items, size):
    """Split items into lists of at most size."""
    if size <= 0:
        raise ValueError("size must be positive")
    batch = []
    for item in items:
        batch.append(item)
        if len(batch) == size:
            yield batch
            batch = []
    if batch:
        yield batch
'''
PY_B = """def chunked(items, size):
    # same helper, kept in sync by hand
    if size <= 0:
        raise ValueError("size must be positive")
    batch = []
    for item in items:
        batch.append(item)
        if len(batch) == size:
            yield batch
            batch = []
    if batch:
        yield batch
"""
GO = """package {name}

func Clamp(value, low, high int) int {{
\tif value < low {{
\t\treturn low
\t}}
\tif value > high {{
\t\treturn high
\t}}
\tfor value%5 != 0 && value < high {{
\t\tvalue++
\t}}
\tif value == high && high-low > 10 {{
\t\treturn high - 1
\t}}
\treturn value
}}
"""
FILES = {
    "packages/shared/src/money.ts": MONEY,
    "apps/web/src/lib/money.ts": MONEY,
    "apps/mobile/src/utils/price.ts": RENAMED,
    "apps/mobile/tests/fixtures.ts": MONEY.split("\n\n")[1],
    "apps/web/src/cart.ts": CART,
    "apps/admin/src/cart.ts": CART.replace(
        "  total(): number {", "  // Sum of every line.\n  total(): number {"
    ),
    "services/api/app/util.py": PY_A,
    "services/worker/app/util.py": PY_B,
    "services/billing/clamp.go": GO.format(name="billing"),
    "services/ledger/clamp.go": GO.format(name="ledger"),
    "services/ledger/db/queries.sql.go": "// Code generated by sqlc. DO NOT EDIT.\n\n"
    + GO.format(name="db"),
    "apps/web/src/routeTree.gen.ts": MONEY,
}


@pytest.fixture()
def call(tmp_path: Path, monkeypatch):
    from database import init_db  # type: ignore

    from graph_os.backends.sqlite_backend import SqliteBackend
    from graph_os.tools import graph
    from graph_os.tools.reindex_dispatch import dispatch

    (tmp_path / ".coding-os").mkdir()
    for relative, text in FILES.items():
        path = tmp_path / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    db = str(tmp_path / "graph.db")
    for relative in FILES:
        dispatch(tmp_path / relative, project_root=tmp_path, db_path=db, include_docs=False)
    test_backend = SqliteBackend(conn=init_db(db))
    monkeypatch.setattr(graph, "_backend", lambda *, backend=None: test_backend)

    def invoke(name: str, **kwargs):
        envelope = getattr(graph, name)(**kwargs)
        return json.loads(envelope) if isinstance(envelope, str) else envelope

    return invoke


def _labels(group: dict) -> set[tuple[str, str]]:
    return {
        (
            member["uid"].split(":", 2)[2].split("::")[0],
            member["uid"].split("::")[-1].split(".")[-1],
        )
        for member in group["members"]
    }


def _group_with(groups: list[dict], file_path: str, label: str) -> dict:
    return next(g for g in groups if (file_path, label) in _labels(g))


def test_an_exact_copy_and_a_renamed_copy_join_one_group(call):
    groups = call("cos_graph_duplicates")["data"]["groups"]
    price = _group_with(groups, "packages/shared/src/money.ts", "formatPrice")

    assert _labels(price) == {
        ("packages/shared/src/money.ts", "formatPrice"),
        ("apps/web/src/lib/money.ts", "formatPrice"),
        ("apps/mobile/src/utils/price.ts", "formatCost"),
    }
    assert price["clone_type"] == "renamed"


def test_exact_mode_keeps_only_identical_bodies(call):
    groups = call("cos_graph_duplicates", clone_type="exact")["data"]["groups"]
    price = _group_with(groups, "packages/shared/src/money.ts", "formatPrice")

    assert ("apps/mobile/src/utils/price.ts", "formatCost") not in _labels(price)
    assert price["clone_type"] == "exact"


def test_a_copied_class_is_one_group_not_one_per_method(call):
    groups = call("cos_graph_duplicates")["data"]["groups"]
    cart = _group_with(groups, "apps/web/src/cart.ts", "Cart")

    assert ("apps/admin/src/cart.ts", "Cart") in _labels(cart)
    assert not any(("apps/web/src/cart.ts", "total") in _labels(g) for g in groups)


def test_python_and_go_copies_are_found(call):
    groups = call("cos_graph_duplicates")["data"]["groups"]

    chunked = _group_with(groups, "services/api/app/util.py", "chunked")
    clamp = _group_with(groups, "services/billing/clamp.go", "Clamp")
    assert ("services/worker/app/util.py", "chunked") in _labels(chunked)
    assert chunked["clone_type"] == "exact"
    assert ("services/ledger/clamp.go", "Clamp") in _labels(clamp)


def test_copied_and_identical_files_are_named(call):
    data = call("cos_graph_duplicates")["data"]

    assert {
        "files": ["apps/web/src/lib/money.ts", "packages/shared/src/money.ts"],
        "shared_symbols": 2,
        "share": [1.0, 1.0],
    } in data["duplicated_files"]
    assert ["apps/web/src/lib/money.ts", "packages/shared/src/money.ts"] in data["identical_files"]


def test_test_copies_are_left_out_unless_asked_and_scope_narrows(call):
    default = call("cos_graph_duplicates")["data"]["groups"]
    with_tests = call("cos_graph_duplicates", include_tests=True)["data"]["groups"]
    scoped = call("cos_graph_duplicates", scope="services/")["data"]["groups"]

    fixture = ("apps/mobile/tests/fixtures.ts", "clampQuantity")
    assert not any(fixture in _labels(g) for g in default)
    assert any(fixture in _labels(g) for g in with_tests)
    assert scoped and all(
        any(m["uid"].split(":", 2)[2].startswith("services/") for m in g["members"]) for g in scoped
    )


def test_similar_ranks_copies_of_the_body_first(call):
    symbol = call(
        "cos_graph_similar", uid="code:function:packages/shared/src/money.ts::formatPrice"
    )
    file = call("cos_graph_similar", uid="code:file:packages/shared/src/money.ts")

    top = {r["uid"]: r["clone_type"] for r in symbol["data"]["results"][:3]}
    assert top == {
        "code:function:apps/web/src/lib/money.ts::formatPrice": "exact",
        "code:function:apps/web/src/routeTree.gen.ts::formatPrice": "exact",
        "code:function:apps/mobile/src/utils/price.ts::formatCost": "renamed",
    }
    assert symbol["data"]["meta"]["clones"] == 3
    identical = {r["uid"] for r in file["data"]["results"] if r.get("clone_type") == "identical"}
    assert "code:file:apps/web/src/lib/money.ts" in identical
    assert file["data"]["results"][0]["similarity"] == 1.0


def test_layout_and_comments_never_change_a_fingerprint():
    from graph_os.extractors import code_python, code_ts

    def hashes(result, label):
        node = next(n for n in result.nodes if n.label == label)
        return node.ast_hash, node.content_hash

    spaced = MONEY.replace("const rounded =", "const   rounded =\n   ")
    assert hashes(code_ts.extract("a.ts", MONEY), "formatPrice") == hashes(
        code_ts.extract("b.ts", "// header\n" + spaced), "formatPrice"
    )
    assert hashes(code_python.extract("a.py", PY_A), "chunked") == hashes(
        code_python.extract("b.py", PY_B), "chunked"
    )


def test_small_bodies_carry_no_fingerprint_and_every_symbol_has_its_end():
    from graph_os.extractors import code_go, code_shell, code_ts

    tiny = next(n for n in code_ts.extract("p.ts", RENAMED).nodes if n.label == "tiny")
    clamp = next(
        n for n in code_go.extract("c.go", GO.format(name="x")).nodes if n.label == "Clamp"
    )
    script = "#!/usr/bin/env bash\nhello() {\n  echo hi\n}\n"
    hello = next(n for n in code_shell.extract("s.sh", script).nodes if n.label == "hello")

    assert (tiny.ast_hash, tiny.content_hash, tiny.end_line) == (None, None, 9)
    assert (clamp.start_line, clamp.end_line) == (3, 17)
    assert clamp.signature == "func Clamp(value, low, high int) int"
    assert (hello.start_line, hello.end_line, hello.ast_hash) == (2, 4, None)


def test_generated_files_are_marked_and_left_out_of_the_report(call):
    data = call("cos_graph_duplicates")["data"]
    clamp = _group_with(data["groups"], "services/billing/clamp.go", "Clamp")

    assert ("services/ledger/db/queries.sql.go", "Clamp") not in _labels(clamp)
    assert not any("routeTree.gen.ts" in path for pair in data["identical_files"] for path in pair)
    assert data["meta"]["generated_files_skipped"] == 2


@pytest.mark.parametrize(
    ("path", "header", "expected"),
    [
        ("db/q.sql.go", "// Code generated by sqlc. DO NOT EDIT.\n", True),
        ("api/x_pb2.py", "", True),
        ("src/routeTree.gen.ts", "", True),
        (
            "src/client.ts",
            "/* eslint-disable */\n// This file was automatically generated.\n",
            True,
        ),
        ("src/schema.ts", "/**\n * @generated by codegen\n */\n", True),
        ("src/util.py", '"""Builds auto-generated docs."""\n', False),
        ("src/do_not_edit.ts", "export const x = 1;\n", False),
    ],
)
def test_is_generated_reads_the_name_and_header_comments(path, header, expected):
    from graph_os.ingest.base import is_generated

    assert is_generated(path, header + "x = 1\n") is expected


def test_offset_pages_through_every_clone_group(call):
    full = call("cos_graph_duplicates", include_tests=True)["data"]
    pages = []
    for offset in range(full["total_count"]):
        page = call("cos_graph_duplicates", include_tests=True, top=1, offset=offset)["data"]
        pages += page["groups"]
        assert page["meta"]["result_truncated"] == (offset + 1 < full["total_count"])

    assert full["total_count"] > 1
    assert [_labels(group) for group in pages] == [_labels(group) for group in full["groups"]]


def test_a_data_table_is_a_clone_only_of_the_same_contents():
    from graph_os.extractors import code_python, code_ts

    keys = ["title", "subtitle", "save", "cancel", "delete", "confirm", "retry", "close", "next"]
    keys += ["back", "done", "skip", "open", "edit"]
    other = ["port", "host", "user", "password", "database", "schema", "timeout", "pool", "ssl"]
    other += ["region", "bucket", "retries", "queue", "topic"]

    def ts_table(name: str, names: list[str], text: str) -> str:
        rows = "".join(f"  {key}: '{text} {key}',\n" for key in names)
        return f"export const {name} = {{\n{rows}}};\n"

    def fingerprints(result) -> dict[str, tuple]:
        return {node.label: (node.ast_hash, node.content_hash) for node in result.nodes}

    ts = fingerprints(
        code_ts.extract(
            "src/i18n.ts",
            ts_table("en", keys, "English")
            + ts_table("fr", keys, "Texte")
            + ts_table("db", other, "English")
            + ts_table("enCopy", keys, "English")
            + "export function greet(name: string) {\n"
            + "  const parts = [name, 'hello', name.length, name.trim(), name.toUpperCase()];\n"
            + "  const joined = parts.map((part) => String(part)).filter(Boolean).join(', ');\n"
            + "  return { joined, count: parts.length, first: parts[0], last: parts.at(-1) };\n}\n"
            + "export function wave(who: string) {\n"
            + "  const parts = [who, 'goodbye', who.length, who.trim(), who.toUpperCase()];\n"
            + "  const joined = parts.map((part) => String(part)).filter(Boolean).join(', ');\n"
            + "  return { joined, count: parts.length, first: parts[0], last: parts.at(-1) };\n}\n"
            + "enum Size { Small = 'small-size', Medium = 'medium-size', Large = 'large-size', "
            + "Huge = 'huge-size', Tiny = 'tiny-size', Wide = 'wide-size', Tall = 'tall-size', "
            + "Flat = 'flat-size', Deep = 'deep-size', Thin = 'thin-size', Long = 'long-size', "
            + "Slim = 'slim-size' }\n"
            + "enum Tone { Small = 'quiet-tone', Medium = 'mild-tone', Large = 'loud-tone', "
            + "Huge = 'harsh-tone', Tiny = 'soft-tone', Wide = 'warm-tone', Tall = 'cold-tone', "
            + "Flat = 'flat-tone', Deep = 'deep-tone', Thin = 'thin-tone', Long = 'long-tone', "
            + "Slim = 'slim-tone' }\n",
        )
    )
    palette = "".join(
        f"    {key!r}: '#{index:02d}{index:02d}AA',\n" for index, key in enumerate(keys)
    )
    py = fingerprints(
        code_python.extract(
            "scripts/palette.py",
            f"DARK = {{\n{palette}}}\n"
            + f"LIGHT = {{\n{palette.replace('AA', 'FF')}}}\n"
            + f"SHADES = {{\n{palette}}}\n",
        )
    )

    assert ts["en"][0] is not None
    assert len({ts["en"][0], ts["fr"][0], ts["db"][0]}) == 3
    assert ts["enCopy"][0] == ts["en"][0] and ts["enCopy"][1] != ts["en"][1]
    assert ts["Size"][0] != ts["Tone"][0]
    assert ts["greet"][0] == ts["wave"][0]
    assert py["DARK"][0] != py["LIGHT"][0]
    assert py["SHADES"][0] == py["DARK"][0]
